# Generated by Django 4.2.19 on 2025-02-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
