# Generated by Django 4.2.19 on 2025-02-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='object_id',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='content_type',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
