# Generated by Django 4.2.19 on 2025-02-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='order',
        ),
        migrations.AddField(
            model_name='shipping',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='carrier',
            field=models.CharField(blank=True, choices=[('grab', 'Grab'), ('j&t', 'J&T'), ('ahamove', 'Ahamove'), ('viettelpost', 'ViettelPost')], default='j&t', max_length=50),
        ),
    ]
